name: Run Tests and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::testthat, any::covr
    - name: Run tests and coverage
      run: |
        R CMD INSTALL .
        Rscript -e 'testthat::test_file("tests/testthat/test-get_git_tags_with_hashes.R")'
        Rscript -e 'covr::codecov()'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
